import jsPDF from "jspdf";
import { Property } from "@/lib/types";

export function generatePropertyPDF(property: Property) {
    const doc = new jsPDF();

    // Header / Brand
    doc.setTextColor(37, 99, 235); // Blue
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Planext CRM", 20, 20);

    doc.setTextColor(100); // Gray
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Premium Real Estate Consultants", 20, 26);

    // Line separator
    doc.setDrawColor(200);
    doc.line(20, 32, 190, 32);

    // Property Title
    doc.setTextColor(0);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(property.title, 20, 45);

    // Status Badge-like text
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.setFillColor(37, 99, 235); // Blue bg
    doc.rect(20, 52, 30, 8, "F");
    doc.text(property.status, 24, 57);

    doc.setFillColor(100); // Gray bg
    doc.rect(55, 52, 30, 8, "F");
    doc.text(property.type, 59, 57);

    // Details Section
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Property Details", 20, 75);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    let y = 85;
    const lineHeight = 10;

    doc.text(`Price: ${property.price}`, 20, y);
    doc.text(`Size: ${property.size}`, 110, y);
    y += lineHeight;

    doc.text(`Location: ${property.location}`, 20, y);
    y += lineHeight;

    doc.text(`Source: ${property.source}`, 20, y);
    y += lineHeight;

    doc.text(`Date Added: ${new Date(property.createdAt).toLocaleDateString()}`, 20, y);
    y += 15;

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Planext CRM", 20, 280);
    doc.text(new Date().toLocaleString(), 150, 280);

    // Save
    doc.save(`${property.title.replace(/\s+/g, "_")}_Brochure.pdf`);
}
